### ISSUE TITLE
Change from viewport size to div size

### ISSUE THREAD

**Issue by mattsafaii** [u2ix/react-background-slider#82]
Can this be used as the background for a Hero section instead of covering the entire viewport.

Is that possible?

**Comment by mattmaker** [comment]
Nevermind I figured it out.

I went to `node_modules > react-background-slider > dist > index.js` and changed the height in css.

**Comment by mattmaker** [comment]
Is there a way to add a media query to the `node_modules > react-background-slider > dist > index.js` file?

I tried adding a media query for the mobile height under:
`"#ReactBackgroundSlider > figure {\n        height: 800px;\n...`

My goal is for a height of 800px on desktop and 600px on mobile.

**Comment by u2ix** [comment]
It's possible to query the screen size inside React and based on that pass different sized images to the component.
For example see this [blog here](https://upmostly.com/tutorials/how-to-use-media-queries-in-react).
